/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MyStoryPdfRouteImport } from './routes/my-story-pdf'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as LoginContinueRouteImport } from './routes/login.continue'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard/library'
import { Route as DashboardDeskRouteImport } from './routes/dashboard/desk'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAccountRouteImport } from './routes/dashboard/account'
import { Route as DashboardBillingIndexRouteImport } from './routes/dashboard/billing/index'
import { Route as DashboardBillingSuccessRouteImport } from './routes/dashboard/billing.success'
import { Route as DashboardBillingCompareRouteImport } from './routes/dashboard/billing.compare'
import { Route as DashboardBillingCheckoutRouteImport } from './routes/dashboard/billing.checkout'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MyStoryPdfRoute = MyStoryPdfRouteImport.update({
  id: '/my-story-pdf',
  path: '/my-story-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const LoginContinueRoute = LoginContinueRouteImport.update({
  id: '/continue',
  path: '/continue',
  getParentRoute: () => LoginRoute,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDeskRoute = DashboardDeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingIndexRoute = DashboardBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardBillingRoute,
} as any)
const DashboardBillingSuccessRoute = DashboardBillingSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => DashboardBillingRoute,
} as any)
const DashboardBillingCompareRoute = DashboardBillingCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => DashboardBillingRoute,
} as any)
const DashboardBillingCheckoutRoute =
  DashboardBillingCheckoutRouteImport.update({
    id: '/checkout',
    path: '/checkout',
    getParentRoute: () => DashboardBillingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/my-story-pdf': typeof MyStoryPdfRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/desk': typeof DashboardDeskRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/login/continue': typeof LoginContinueRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/billing/checkout': typeof DashboardBillingCheckoutRoute
  '/dashboard/billing/compare': typeof DashboardBillingCompareRoute
  '/dashboard/billing/success': typeof DashboardBillingSuccessRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRouteWithChildren
  '/my-story-pdf': typeof MyStoryPdfRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/desk': typeof DashboardDeskRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/login/continue': typeof LoginContinueRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/billing/checkout': typeof DashboardBillingCheckoutRoute
  '/dashboard/billing/compare': typeof DashboardBillingCompareRoute
  '/dashboard/billing/success': typeof DashboardBillingSuccessRoute
  '/dashboard/billing': typeof DashboardBillingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/my-story-pdf': typeof MyStoryPdfRoute
  '/privacy': typeof PrivacyRoute
  '/signup': typeof SignupRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/billing': typeof DashboardBillingRouteWithChildren
  '/dashboard/desk': typeof DashboardDeskRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/login/continue': typeof LoginContinueRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/billing/checkout': typeof DashboardBillingCheckoutRoute
  '/dashboard/billing/compare': typeof DashboardBillingCompareRoute
  '/dashboard/billing/success': typeof DashboardBillingSuccessRoute
  '/dashboard/billing/': typeof DashboardBillingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-story-pdf'
    | '/privacy'
    | '/signup'
    | '/sso-callback'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/dashboard/account'
    | '/dashboard/billing'
    | '/dashboard/desk'
    | '/dashboard/library'
    | '/login/continue'
    | '/dashboard/'
    | '/dashboard/billing/checkout'
    | '/dashboard/billing/compare'
    | '/dashboard/billing/success'
    | '/dashboard/billing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/my-story-pdf'
    | '/privacy'
    | '/signup'
    | '/sso-callback'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/dashboard/account'
    | '/dashboard/desk'
    | '/dashboard/library'
    | '/login/continue'
    | '/dashboard'
    | '/dashboard/billing/checkout'
    | '/dashboard/billing/compare'
    | '/dashboard/billing/success'
    | '/dashboard/billing'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/my-story-pdf'
    | '/privacy'
    | '/signup'
    | '/sso-callback'
    | '/terms'
    | '/verify-email'
    | '/welcome'
    | '/dashboard/account'
    | '/dashboard/billing'
    | '/dashboard/desk'
    | '/dashboard/library'
    | '/login/continue'
    | '/dashboard/'
    | '/dashboard/billing/checkout'
    | '/dashboard/billing/compare'
    | '/dashboard/billing/success'
    | '/dashboard/billing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  MyStoryPdfRoute: typeof MyStoryPdfRoute
  PrivacyRoute: typeof PrivacyRoute
  SignupRoute: typeof SignupRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-story-pdf': {
      id: '/my-story-pdf'
      path: '/my-story-pdf'
      fullPath: '/my-story-pdf'
      preLoaderRoute: typeof MyStoryPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/login/continue': {
      id: '/login/continue'
      path: '/continue'
      fullPath: '/login/continue'
      preLoaderRoute: typeof LoginContinueRouteImport
      parentRoute: typeof LoginRoute
    }
    '/dashboard/library': {
      id: '/dashboard/library'
      path: '/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/desk': {
      id: '/dashboard/desk'
      path: '/desk'
      fullPath: '/dashboard/desk'
      preLoaderRoute: typeof DashboardDeskRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing/': {
      id: '/dashboard/billing/'
      path: '/'
      fullPath: '/dashboard/billing/'
      preLoaderRoute: typeof DashboardBillingIndexRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
    '/dashboard/billing/success': {
      id: '/dashboard/billing/success'
      path: '/success'
      fullPath: '/dashboard/billing/success'
      preLoaderRoute: typeof DashboardBillingSuccessRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
    '/dashboard/billing/compare': {
      id: '/dashboard/billing/compare'
      path: '/compare'
      fullPath: '/dashboard/billing/compare'
      preLoaderRoute: typeof DashboardBillingCompareRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
    '/dashboard/billing/checkout': {
      id: '/dashboard/billing/checkout'
      path: '/checkout'
      fullPath: '/dashboard/billing/checkout'
      preLoaderRoute: typeof DashboardBillingCheckoutRouteImport
      parentRoute: typeof DashboardBillingRoute
    }
  }
}

interface DashboardBillingRouteChildren {
  DashboardBillingCheckoutRoute: typeof DashboardBillingCheckoutRoute
  DashboardBillingCompareRoute: typeof DashboardBillingCompareRoute
  DashboardBillingSuccessRoute: typeof DashboardBillingSuccessRoute
  DashboardBillingIndexRoute: typeof DashboardBillingIndexRoute
}

const DashboardBillingRouteChildren: DashboardBillingRouteChildren = {
  DashboardBillingCheckoutRoute: DashboardBillingCheckoutRoute,
  DashboardBillingCompareRoute: DashboardBillingCompareRoute,
  DashboardBillingSuccessRoute: DashboardBillingSuccessRoute,
  DashboardBillingIndexRoute: DashboardBillingIndexRoute,
}

const DashboardBillingRouteWithChildren =
  DashboardBillingRoute._addFileChildren(DashboardBillingRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardBillingRoute: typeof DashboardBillingRouteWithChildren
  DashboardDeskRoute: typeof DashboardDeskRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardBillingRoute: DashboardBillingRouteWithChildren,
  DashboardDeskRoute: DashboardDeskRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

interface LoginRouteChildren {
  LoginContinueRoute: typeof LoginContinueRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginContinueRoute: LoginContinueRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  MyStoryPdfRoute: MyStoryPdfRoute,
  PrivacyRoute: PrivacyRoute,
  SignupRoute: SignupRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
